apiVersion: v1
kind: PersistentVolume

metadata:
  name: vectorstore-pv

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /data/vectorstore

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: vectorstore-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi